[general]
import = [
   "~/.config/alacritty/themes/themes/midnight_haze.toml"
]
live_config_reload = true

[window]
dimensions = { columns = 104, lines = 28 }
opacity = 0.80
dynamic_padding = true
# blur = true 
startup_mode = "Maximized"
dynamic_title = false

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 10

[cursor]
style = { blinking = "Always" }
blink_interval = 350

# [env]
# TERM = "xterm" # This does not support 'truecolor' in within tmux session
